# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: counter
    binary: eldenring-death-counter
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    ignore:
      - goarch: "386"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Katrovsky
    name: EldenRingDC
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
